baseURL = 'https://example.org/'
locale = 'en-us'
title = 'AziTech'
theme = 'hugo-bearblog'

[module]
  [[module.imports]]
    path = "github.com/privatemaker/headless-cms"

[outputs]
  home = ["HTML", "RSS", "HeadlessCMSConfig"]
