backend:
  name: github
  repo: azilamo-jp/azitech
collections:
- create: true
  fields:
  - label: Title
    name: title
    widget: string
  - label: Body
    name: body
    widget: markdown
  - label: Date
    name: date
    widget: datetime
  - default: true
    label: Draft
    name: draft
    widget: boolean
  folder: content/blog
  label: Posts
  name: posts
locale: en-us
media_folder: static/uploads
public_folder: /uploads
search: true
site_url: https://tech.azilamo.dev/
